server:
  port: 8100
  error:
    include-message: always
spring:
  kafka:
    producer:
      bootstrap-servers:
        - kafka:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties:
        spring.json.trusted.packages: "*"
      bootstrap-servers:
        - kafka:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      group-id: app
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_jdbc_metadata_defaults: false
        ddl-auto: update
    show-sql: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8190/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}